COMMON = (
    "OPENFEMM",
    "CLEARCONSOLE",
    "NEWDOCUMENT",
    "HIDECONSOLE",
    "HIDEPOINTPROPS",
    "MESSAGEBOX",
    "OPENDOCUMENT"
    "PRINT",
    "PROMPT",
    "SHOWCONSOLE",
    "SHOWPOINTPROPS",
    "SMARTMESH",
    "MAIN_MINIMIZE",
    "MAIN_MAXIMISE",
    "MAIN_RESTORE",
    "MAIN_RESIZE"
)